"use client"

import { citationById } from "@/data/citations"
import type { FormalDoc } from "@/types"

type Props = {
  doc: FormalDoc
  onCite?: (id: string) => void
  activeId?: string | null
}

function partyBlock(p: FormalDoc["parties"][0], index: number) {
  const so = p.parent ? `, ${p.parent}` : ""
  const age = p.age ? `, aged about ${p.age} years` : ""
  return (
    <p key={p.capacity}>
      <strong>
        {index === 0 ? "BETWEEN" : "AND"} {p.name || `[${p.capacity}]`}
      </strong>
      {so}
      {age}, residing at {p.address || "[address]"} (hereinafter referred to as the "{p.capacity}", which expression
      shall, unless repugnant to the context, include heirs, successors and permitted assigns).
    </p>
  )
}

export function FormalPaper({ doc, onCite, activeId }: Props) {
  const ids = [...new Set(doc.clauses.flatMap((c) => c.citationIds))]

  return (
    <article id="contract-paper" className="deed">
      <div className="deed-stamp">
        <p>STAMP / E-STAMP</p>
        <p>{doc.stampLine}</p>
      </div>
      <h1 className="deed-title">{doc.title}</h1>
      <p className="deed-made">
        THIS AGREEMENT is made at <strong>{doc.place || "[city], [State]"}</strong> on this{" "}
        <strong>{doc.date || "[date]"}</strong>.
      </p>
      {doc.parties.map((p, i) => partyBlock(p, i))}
      <p className="deed-label">WHEREAS:</p>
      <ol className="deed-whereas">
        {doc.recitals.map((r) => (
          <li key={r}>{r}</li>
        ))}
      </ol>
      <p className="deed-label">NOW THIS AGREEMENT WITNESSETH AS FOLLOWS:</p>
      {doc.clauses.map((clause, idx) => (
        <section key={clause.id} className="deed-clause">
          <h2>
            {idx + 1}. {clause.heading.replace(/^\d+\.\s*/, "")}
          </h2>
          <p>{clause.body}</p>
          <p className="paper-cites">
            {clause.citationIds.map((id) => {
              const c = citationById(id)
              if (!c) return null
              const n = ids.indexOf(id) + 1
              return (
                <button
                  key={`${clause.id}-${id}`}
                  type="button"
                  className={activeId === id ? "cite is-on" : "cite"}
                  onClick={() => onCite?.(id)}
                >
                  [{n}] {c.short}
                </button>
              )
            })}
          </p>
        </section>
      ))}
      {doc.stateNote ? <p className="deed-note">{doc.stateNote}</p> : null}
      <p className="deed-label">IN WITNESS WHEREOF</p>
      <p>
        the parties have executed this Agreement on the date first written above, in the presence of the undersigned
        witnesses.
      </p>
      <table className="deed-sign">
        <tbody>
          <tr>
            <td>
              <p>For the {doc.roleA}</p>
              <p className="line">Signature</p>
              <p>Name:</p>
              <p>Date / Place:</p>
            </td>
            <td>
              <p>For the {doc.roleB}</p>
              <p className="line">Signature</p>
              <p>Name:</p>
              <p>Date / Place:</p>
            </td>
          </tr>
          <tr>
            <td>
              <p>Witness 1</p>
              <p className="line">Signature</p>
              <p>Name / Address:</p>
            </td>
            <td>
              <p>Witness 2</p>
              <p className="line">Signature</p>
              <p>Name / Address:</p>
            </td>
          </tr>
        </tbody>
      </table>
      <ol className="footnotes">
        {ids.map((id, i) => {
          const c = citationById(id)
          if (!c) return null
          return (
            <li key={id}>
              <strong>
                [{i + 1}] {c.act}, s. {c.section}.
              </strong>{" "}
              {c.summary}{" "}
              <a href={c.sourceUrl} target="_blank" rel="noreferrer">
                Official text (India Code)
              </a>
              . Last checked {c.lastChecked}.
            </li>
          )
        })}
      </ol>
      <p className="deed-foot">Reference draft generated by ConDraft. Not legal advice. Not a substitute for an advocate.</p>
    </article>
  )
}
